Repository NadyaHuryan/FE91, pull requests merged in 2022-10, with the labels that each got.

#10 Kseniya Bokaya(hw_0): My first pull request
  lesson-0/hw-0.md
  lesson-0/hw_0js.js
  lesson-0/index_hw_0.html
Labels: valid

#9 Alena Khatkevich home_work_o
  lesson-0/hw_0.js
  lesson-0/index.html
Labels: valid

#1 Andrey Kalenik [hw_0]: My first pull request
  index.html
  lesson-0/hw_1.js
Labels: valid

#2 ivan.ignatkin[hw_0]: My first pull request
  lesson-0/hw_0.js
  lesson-0/index.html
Labels: valid

#3 Roman Glinnik [hw_0]: My first pull request
  lesson-0/hw_0.js
  lesson-0/index.html
Labels: valid

#4 Siarhei.puzatka [hw_1]: My first pull request
  lesson-0/hw_1.js
  lesson-0/index.html
Labels: valid

#5 Catherine Krichkovskaya [hw_0]: My first pull request
  lesson-0/hw_0.js
  lesson-0/index.html
Labels: valid

#7 Dima Velesevich [hw_0]: Home work 0
  lesson-0/hw_0.js
  lesson-0/index.html
Labels: valid

#14 Andrey.Kalenik [hw_01] || rewrite boring exercises
  lesson-0/index.html
  lesson-1/hw-1.md
  lesson-1/index.html
  lesson-1/script.js
Labels: valid

#15 Aliona Kragel [hw_1]: First homework Javascrip
  lesson-1/index.html
  lesson-1/script.js
Labels: ready for review, valid, comments in code

#18 Kseniya.b hw 1
  lesson-0/hw-0.md
  lesson-1/hw-1.md
  lesson-1/index.html
  lesson-1/js-hw_1.js
Labels: valid

#19 Roman Glinnik [hw_1]: Ready home work 1
  lesson-1/hw-1.md
  lesson-1/index.html
  lesson-1/script.js
Labels: valid

#21 pull request Ivan.ignatkin hw 1
  lesson-1/hw-1.md
  lesson-1/index.html
  lesson-1/script.js
Labels: valid, comments in code

#23 alena.khatkevich [hw_1]: homework_1
  lesson-0/lesson-0/hw-0.md
  lesson-0/lesson-0/hw-1.md
  lesson-0/lesson-0/hw_0.js
  lesson-0/lesson-0/hw_1.js
  lesson-0/lesson-0/index.html
  lesson-0/lesson-0/script.js
Labels: valid

#24 Malchikova Liza [Hw_1]
  lesson-0/hw-0.md
  lesson-1/hw-1.md
  lesson-1/index.html
  lesson-1/script.js
Labels: ready for review

#25 Catherine Krichkovskaya [hw_1]: First homework check
  lesson-1/hw-1.md
  lesson-1/hw_1.js
Labels: ready for review

#26 Ivan.ignatkin hw 2
  Classwork/lesson-1/TMS-Basic-JS.lesson-2.pdf
  Classwork/lesson-1/code-style.svg
  Classwork/lesson-1/index.html
  Classwork/lesson-1/index.js
  Classwork/lesson-1/script.js
  lesson-2/hw-2.md
  lesson-2/index.html
  lesson-2/script.js
Labels: valid, comments in code

#27 Aliona Kragel [hw_2]
  .gitignore
  Classwork/lesson-1/TMS-Basic-JS.lesson-2.pdf
  Classwork/lesson-1/code-style.svg
  Classwork/lesson-1/index.html
  Classwork/lesson-1/index.js
  Classwork/lesson-1/script.js
  lesson-2/hw-2.md
  lesson-2/index.html
  lesson-2/script.js
Labels: valid, comments in code

#22 andrey.kalenik [hw_02]: logical operators, conditional branching and loops
  lesson-2/index.html
  lesson-2/script.js
Labels: valid, comments in code
