Repository NadyaHuryan/FE91, pull requests merged in 2022-11, with the labels that each got.

#28 Kseniya Bokaya [hw_2]
  .vscode/settings.json
  Classwork/lesson-1/TMS-Basic-JS.lesson-2.pdf
  Classwork/lesson-1/code-style.svg
  Classwork/lesson-1/index.html
  Classwork/lesson-1/index.js
  Classwork/lesson-1/script.js
  lesson-2/hw-2.md
  lesson-2/index.html
  lesson-2/js-hw_2.js
Labels: ready for review

#35 Liza.malchikova-hw_2: loops, operators
  Classwork/lesson-1/TMS-Basic-JS.lesson-2.pdf
  Classwork/lesson-1/code-style.svg
  Classwork/lesson-1/index.html
  Classwork/lesson-1/index.js
  Classwork/lesson-1/script.js
  Classwork/lesson-2/JavaScript-if-else-statment.png
  Classwork/lesson-2/TMS-Basic-JS.lesson-3.pdf
  Classwork/lesson-2/flowchart_nested_conditional.png
  Classwork/lesson-2/index.html
  Classwork/lesson-2/script.js
  Classwork/lesson-2/unnamed.gif
  lesson-0/hw-0.js
  lesson-0/index.html
  lesson-2/hw-2.md
  lesson-2/hw_2.html
  lesson-2/hw_2.js
  lesson-3/hw-3.md
Labels: valid, comments in code

#30 Roman.glinnik hw 2
  Classwork/lesson-1/TMS-Basic-JS.lesson-2.pdf
  Classwork/lesson-1/code-style.svg
  Classwork/lesson-1/index.html
  Classwork/lesson-1/index.js
  Classwork/lesson-1/script.js
  lesson-2/hw-2.md
  lesson-2/index.html
  lesson-2/script.js
Labels: ready for review

#29 Second homework
  Classwork/lesson-1/TMS-Basic-JS.lesson-2.pdf
  Classwork/lesson-1/code-style.svg
  Classwork/lesson-1/index.html
  Classwork/lesson-1/index.js
  Classwork/lesson-1/script.js
  Classwork/lesson-2/JavaScript-if-else-statment.png
  Classwork/lesson-2/TMS-Basic-JS.lesson-3.pdf
  Classwork/lesson-2/flowchart_nested_conditional.png
  Classwork/lesson-2/index.html
  Classwork/lesson-2/script.js
  Classwork/lesson-2/unnamed.gif
  lesson-2/hw-2.md
  lesson-2/hw_2.js
  lesson-3/hw-3.md
Labels: valid, comments in code

#33 Puzatka.siarhei hw 2
  Classwork/lesson-1/TMS-Basic-JS.lesson-2.pdf
  Classwork/lesson-1/code-style.svg
  Classwork/lesson-1/index.html
  Classwork/lesson-1/index.js
  Classwork/lesson-1/script.js
  Classwork/lesson-2/JavaScript-if-else-statment.png
  Classwork/lesson-2/TMS-Basic-JS.lesson-3.pdf
  Classwork/lesson-2/flowchart_nested_conditional.png
  Classwork/lesson-2/index.html
  Classwork/lesson-2/script.js
  Classwork/lesson-2/unnamed.gif
  lesson-2/hw-2.md
  lesson-2/index.html
  lesson-2/script.js
Labels: need to fix, ready for review, comments in code

#36 andrey.kalenik [hw 03] || function
  Classwork/lesson-2/JavaScript-if-else-statment.png
  Classwork/lesson-2/TMS-Basic-JS.lesson-3.pdf
  Classwork/lesson-2/flowchart_nested_conditional.png
  Classwork/lesson-2/index.html
  Classwork/lesson-2/script.js
  Classwork/lesson-2/unnamed.gif
  lesson-3/hw-3.md
  lesson-3/index.html
  lesson-3/script.js
  lesson-3/test.js
  lesson-3/формула кредита.jpg
Labels: valid, comments in code

#37 Roman Glinnik [hw_3]: Function tasks
  Classwork/lesson-2/JavaScript-if-else-statment.png
  Classwork/lesson-2/TMS-Basic-JS.lesson-3.pdf
  Classwork/lesson-2/flowchart_nested_conditional.png
  Classwork/lesson-2/index.html
  Classwork/lesson-2/script.js
  Classwork/lesson-2/unnamed.gif
  lesson-3/hw-3.md
  lesson-3/index.html
  lesson-3/script.js
Labels: ready for review

#34 Alena Khatkevich [hw_2]: add hw_2
  Classwork/lesson-1/TMS-Basic-JS.lesson-2.pdf
  Classwork/lesson-1/code-style.svg
  Classwork/lesson-1/index.html
  Classwork/lesson-1/index.js
  Classwork/lesson-1/script.js
  Classwork/lesson-2/JavaScript-if-else-statment.png
  Classwork/lesson-2/TMS-Basic-JS.lesson-3.pdf
  Classwork/lesson-2/flowchart_nested_conditional.png
  Classwork/lesson-2/index.html
  Classwork/lesson-2/script.js
  Classwork/lesson-2/unnamed.gif
  lesson-2/hw-2.md
  lesson-2/hw_2.js
  lesson-2/index.html
  lesson-3/hw-3.md
Labels: valid, comments in code

#39 Kseniya Bokaya [hw_3]: Functions
  Classwork/lesson-2/JavaScript-if-else-statment.png
  Classwork/lesson-2/TMS-Basic-JS.lesson-3.pdf
  Classwork/lesson-2/flowchart_nested_conditional.png
  Classwork/lesson-2/index.html
  Classwork/lesson-2/script.js
  Classwork/lesson-2/unnamed.gif
  Classwork/lesson-3 function/TMS-Basic-JS.lesson-4.pdf
  Classwork/lesson-3 function/index.html
  Classwork/lesson-3 function/script.js
  Classwork/lesson-3 function/summary-4.pdf
  lesson-3/hw-3.md
  lesson-3/index.html
  lesson-3/js-hw_3.js
Labels: valid

#47 init(hw_1): start course Javascript Basic
  lesson-1/hw_1.js
Labels: ready for review

#41 Liza Malchikova [hw_3]: functions
  lesson-2/hw_2.js
  lesson-3/hw_3.html
  lesson-3/hw_3.js
Labels: ready for review

#43 DimaVelesevich[hw 3]
  Classwork/lesson-1/TMS-Basic-JS.lesson-2.pdf
  Classwork/lesson-1/code-style.svg
  Classwork/lesson-1/index.html
  Classwork/lesson-1/index.js
  Classwork/lesson-1/script.js
  Classwork/lesson-2/JavaScript-if-else-statment.png
  Classwork/lesson-2/TMS-Basic-JS.lesson-3.pdf
  Classwork/lesson-2/flowchart_nested_conditional.png
  Classwork/lesson-2/index.html
  Classwork/lesson-2/script.js
  Classwork/lesson-2/unnamed.gif
  Classwork/lesson-3 function/TMS-Basic-JS.lesson-4.pdf
  Classwork/lesson-3 function/index.html
  Classwork/lesson-3 function/script.js
  Classwork/lesson-3 function/summary-4.pdf
  lesson-1/hw-1.md
  lesson-2/hw-2.md
  lesson-3/hw-3.md
  lesson-3/hw_3.js
  lesson-3/index.html
  lesson-4 array/hw-4.md
Labels: ready for review

#44 Catherine Krichkovskaya [hw_3]: third homework
  lesson-3/hw_3.js
Labels: valid

#46 Alena Khatkevich [hw_3]: add hw-3
  Classwork/lesson-3 function/TMS-Basic-JS.lesson-4.pdf
  Classwork/lesson-3 function/index.html
  Classwork/lesson-3 function/script.js
  Classwork/lesson-3 function/summary-4.pdf
  lesson-2/hw_2.js
  lesson-3/hw_3.js
  lesson-3/index.html
  lesson-4 array/hw-4.md
Labels: ready for review

#48 Roman Glinnik [hw_4]: Ready array tasks
  Classwork/lesson-3 function/TMS-Basic-JS.lesson-4.pdf
  Classwork/lesson-3 function/index.html
  Classwork/lesson-3 function/script.js
  Classwork/lesson-3 function/summary-4.pdf
  lesson-4 array/hw-4.md
  lesson-4 array/index.html
  lesson-4 array/script.js
Labels: valid

#49 Aliona Kragel [hw_4]: Array
  Classwork/lesson-3 function/TMS-Basic-JS.lesson-4.pdf
  Classwork/lesson-3 function/index.html
  Classwork/lesson-3 function/script.js
  Classwork/lesson-3 function/summary-4.pdf
  lesson-4 array/hw-4.md
  lesson-4 array/index.html
  lesson-4 array/script.js
Labels: ready for review

#51 Vlad.xaosens hw4
  Classwork/lesson-3 function/TMS-Basic-JS.lesson-4.pdf
  Classwork/lesson-3 function/index.html
  Classwork/lesson-3 function/script.js
  Classwork/lesson-3 function/summary-4.pdf
  Classwork/lesson-4 array/TMS-Basic-JS.lesson-6.pdf
  Classwork/lesson-4 array/index.html
  Classwork/lesson-4 array/script.js
  Classwork/lesson-4 array/summary-6.pdf
  lesson-2/script.js
  lesson-4 array/hw-4.md
  lesson-4 array/index.html
  lesson-4 array/script.js
Labels: valid

#52 T.Ratkevich [hw_4]
  lesson-4 array/hw_4.js
  lesson-4 array/index.html
Labels: valid

#50 Dima.velesevich [hw_4]
  Classwork/lesson-4 array/TMS-Basic-JS.lesson-6.pdf
  Classwork/lesson-4 array/index.html
  Classwork/lesson-4 array/script.js
  Classwork/lesson-4 array/summary-6.pdf
  lesson-4 array/hw_4.js
  lesson-4 array/index.html
Labels: valid

#56 andrey.kalenik [hw 04] : Arrays
  lesson-4 array/index.html
  lesson-4 array/script.js
  lesson-4 array/task9.PNG
  lesson-4 array/test.js
Labels: valid

#54 Liza.malchikova [hw-4]: arrays
  Classwork/lesson-3 function/TMS-Basic-JS.lesson-4.pdf
  Classwork/lesson-3 function/index.html
  Classwork/lesson-3 function/script.js
  Classwork/lesson-3 function/summary-4.pdf
  Classwork/lesson-4 array/TMS-Basic-JS.lesson-6.pdf
  Classwork/lesson-4 array/index.html
  Classwork/lesson-4 array/script.js
  Classwork/lesson-4 array/summary-6.pdf
  lesson-4 array/hw-4.html
  lesson-4 array/hw-4.js
  lesson-4 array/hw-4.md
  lesson-5 object/hw-5.md
Labels: valid, comments in code

#55 Kseniya Bokaya [hw_4]: Array
  Classwork/lesson-4 array/TMS-Basic-JS.lesson-6.pdf
  Classwork/lesson-4 array/index.html
  Classwork/lesson-4 array/script.js
  Classwork/lesson-4 array/summary-6.pdf
  lesson-4 array/hw-4.md
  lesson-4 array/index.html
  lesson-4 array/js-hw_4.js
  lesson-5 object/hw-5.md
Labels: valid

#57 Catherine Krichkovskaya [hw_4] Arrays
  Classwork/lesson-3 function/TMS-Basic-JS.lesson-4.pdf
  Classwork/lesson-3 function/index.html
  Classwork/lesson-3 function/script.js
  Classwork/lesson-3 function/summary-4.pdf
  lesson-4 array/hw-4.md
  lesson-4 array/hw_4.js
Labels: valid

#58 Alena Khatkevich [hw_4]: array
  Classwork/lesson-4 array/TMS-Basic-JS.lesson-6.pdf
  Classwork/lesson-4 array/index.html
  Classwork/lesson-4 array/script.js
  Classwork/lesson-4 array/summary-6.pdf
  lesson-4 array/hw_4.js
  lesson-4 array/index.html
  lesson-4 array/tempCodeRunnerFile.js
  lesson-5 object/hw-5.md
  lesson-5 object/hw_5.js
  lesson-5 object/index.html
Labels: ready for review

#45 Ivan.ignatkin hw 3
  Classwork/lesson-2/JavaScript-if-else-statment.png
  Classwork/lesson-2/TMS-Basic-JS.lesson-3.pdf
  Classwork/lesson-2/flowchart_nested_conditional.png
  Classwork/lesson-2/index.html
  Classwork/lesson-2/script.js
  Classwork/lesson-2/unnamed.gif
  Classwork/lesson-3 function/TMS-Basic-JS.lesson-4.pdf
  Classwork/lesson-3 function/index.html
  Classwork/lesson-3 function/script.js
  Classwork/lesson-3 function/summary-4.pdf
  lesson-3/hw-3.md
  lesson-3/index.html
  lesson-3/script.js
Labels: valid

#59 Alena Khatkevich [hw_5]: object
  Classwork/lesson-5 object/TMS-Basic-JS.lesson-5.pdf
  Classwork/lesson-5 object/index.html
  Classwork/lesson-5 object/script.js
  Classwork/lesson-5 object/summary-5.pdf
  lesson-5 object/hw_5.js
  lesson-5 object/index.html
Labels: valid

#60 andrey.kalenik [hw 05] || Objects
  classwork_debt_table_multiplay/index.html
  classwork_debt_table_multiplay/script.js
  classwork_debt_table_multiplay/style.css
  lesson-5 object/index.html
  lesson-5 object/script.js
Labels: valid

#61 Aliona Kragel [hw_5]: Object
  Classwork/lesson-4 array/TMS-Basic-JS.lesson-6.pdf
  Classwork/lesson-4 array/index.html
  Classwork/lesson-4 array/script.js
  Classwork/lesson-4 array/summary-6.pdf
  lesson-4 array/script.js
  lesson-5 object/hw-5.md
  lesson-5 object/index.html
  lesson-5 object/script.js
Labels: valid

#62 Ivan.ignatkin [hw 4] first pull request
  Classwork/lesson-4 array/TMS-Basic-JS.lesson-6.pdf
  Classwork/lesson-4 array/index.html
  Classwork/lesson-4 array/script.js
  Classwork/lesson-4 array/summary-6.pdf
  Classwork/lesson-5 object/TMS-Basic-JS.lesson-5.pdf
  Classwork/lesson-5 object/index.html
  Classwork/lesson-5 object/script.js
  Classwork/lesson-5 object/summary-5.pdf
  Classwork/lesson-5.1 test/index.html
  Classwork/lesson-5.1 test/test.js
  lesson-4 array/hw-4.md
  lesson-4 array/index.html
  lesson-4 array/script.js
  lesson-5 object/hw-5.md
  lesson-6 array + func/hw-6.md
Labels: ready for review

#63 Catherine Krichkovskaya [hw 5]: Objects homework
  Classwork/lesson-4 array/TMS-Basic-JS.lesson-6.pdf
  Classwork/lesson-4 array/index.html
  Classwork/lesson-4 array/script.js
  Classwork/lesson-4 array/summary-6.pdf
  lesson-5 object/hw-5.md
  lesson-5 object/hw_5.js
  lesson-5 object/index.html
Labels: valid

#71 Vlad Xxaosens hw-3
  lesson-3/index.html
  lesson-3/script.js
Labels: valid

#67 Kseniya Bokaya [hw_5]: Objects
  Classwork/lesson-5 object/TMS-Basic-JS.lesson-5.pdf
  Classwork/lesson-5 object/index.html
  Classwork/lesson-5 object/script.js
  Classwork/lesson-5 object/summary-5.pdf
  Classwork/lesson-5.1 test/index.html
  Classwork/lesson-5.1 test/test.js
  lesson-1/hw_1.js
  lesson-4 array/hw_4.js
  lesson-5 object/index.html
  lesson-5 object/js-hw_5.js
  lesson-6 array + func/hw-6.md
Labels: valid

#72 T.Ratkevich [hw_5]
  Classwork/lesson-5 object/TMS-Basic-JS.lesson-5.pdf
  Classwork/lesson-5 object/index.html
  Classwork/lesson-5 object/script.js
  Classwork/lesson-5 object/summary-5.pdf
  Classwork/lesson-5.1 test/index.html
  Classwork/lesson-5.1 test/test.js
  lesson-5 object/hw-5.md
  lesson-5 object/hw_5.js
  lesson-5 object/index.html
  lesson-6 array + func/hw-6.md
Labels: valid

#68 Roman Glinnik [hw_5]: done object tasks
  Classwork/lesson-4 array/TMS-Basic-JS.lesson-6.pdf
  Classwork/lesson-4 array/index.html
  Classwork/lesson-4 array/script.js
  Classwork/lesson-4 array/summary-6.pdf
  lesson-5 object/hw-5.md
  lesson-5 object/index.html
  lesson-5 object/script.js
Labels: valid

#76 Siarhei Puzatka [hw_5]: Objects
  lesson-4 array/script.js
  lesson-5 object/hw-5.md
  lesson-5 object/index.html
  lesson-5 object/script.js
Labels: valid

#66 Aliona Kragel [hw_6]: Array methods
  Classwork/lesson-5 object/TMS-Basic-JS.lesson-5.pdf
  Classwork/lesson-5 object/index.html
  Classwork/lesson-5 object/script.js
  Classwork/lesson-5 object/summary-5.pdf
  Classwork/lesson-5.1 test/index.html
  Classwork/lesson-5.1 test/test.js
  lesson-6 array + func/hw-6.md
  lesson-6 array + func/index.html
  lesson-6 array + func/script.js
Labels: valid
